timepoints:
  - time_in_seconds: 0
    concentration: 0
    unit_conc: ng/ml
  - time_in_seconds: 5400
    concentration: 70
    unit_conc: ng/ml
  - time_in_seconds: 10800
    concentration: 120
    unit_conc: ng/ml
  - time_in_seconds: 21600
    concentration: 300
    unit_conc: ng/ml
  - time_in_seconds: 32400
    concentration: 600
    unit_conc: ng/ml
  - time_in_seconds: 37800
    concentration: 200
    unit_conc: ng/ml
  - time_in_seconds: 43200
    concentration: 0
    unit_conc: ng/ml
